insert into groups values (1,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'PROGRAMMERS', '611p','IVAN KORNIIENKO');
insert into groups values (2,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'ECONOMISTS', '621er','MORGAN FREEMAN');
insert into groups values (3,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'PROGRAMMERS', '632p','JOANNE ROWLING');
insert into groups values (4,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'ECONOMISTS','511e','LEBRON JAMES');
insert into groups values (5,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'PROGRAMMERS','411p','LEO MESSI');
insert into groups values (6,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'ECONOMISTS','411e','IVAN KORNIIENKO');
insert into groups values (7,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'ECONOMISTS','611e','LEBRON JAMES');
insert into groups values (8,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'ECONOMISTS','622e','MORGAN FREEMAN');
insert into groups values (9,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'MARKETERS','621m','IVAN KORNIIENKO');
insert into groups values (10,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'PROGRAMMERS','623p','JOANNE ROWLING');
insert into groups values (11,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'PROGRAMMERS','631p','IVAN KORNIIENKO');
insert into groups values (12,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'MARKETERS','611m','MORGAN FREEMAN');
insert into groups values (13,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'MARKETERS','611m','LEBRON JAMES');

insert into students values (1,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'11','Aneta','Adaline');
insert into students values (2,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'22','Assumpció','Grusha');
insert into students values (3,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'33','Świętopełk','Zacharias');
insert into students values (4,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'44','Nikoloz','Samuil');
insert into students values (5,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'45','Melissza','Artemio');
insert into students values (6,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'66','Kenya','Nuka');
insert into students values (7,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'23','Candelario','Navin');
insert into students values (8,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'47','Miroslava','Rada');
insert into students values (9,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'41','Agata','Avdotya');
insert into students values (10,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'14','Vasily','Anisim');
insert into students values (11,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'18','Natalya','Markin');
insert into students values (12,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'46','Natalya','Feofil');
insert into students values (13,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'23','Lyudmila','Markin');
insert into students values (14,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'19','Ivan','Dmitrii');
insert into students values (15,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'19','Avdey','Markin');
insert into students values (16,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'36','Lyudmila','Grusha');
insert into students values (17,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'37','Avdey','Feofil');

insert into groups_students values (1,17);
insert into groups_students values (1,16);
insert into groups_students values (1,15);
insert into groups_students values (1,14);
insert into groups_students values (2,14);
insert into groups_students values (2,15);
insert into groups_students values (2,16);
insert into groups_students values (3,6);
insert into groups_students values (3,7);
insert into groups_students values (3,8);
insert into groups_students values (4,11);
insert into groups_students values (4,12);
insert into groups_students values (5,15);
insert into groups_students values (6,14);
insert into groups_students values (7,6);
insert into groups_students values (8,6);
insert into groups_students values (8,5);
insert into groups_students values (8,4);
insert into groups_students values (8,3);
insert into groups_students values (8,2);
insert into groups_students values (9,1);
insert into groups_students values (11,7);
insert into groups_students values (12,7);
insert into groups_students values (12,8);
insert into groups_students values (12,9);
insert into groups_students values (12,13);
insert into groups_students values (12,12);
insert into groups_students values (12,15);