insert into groups values (1,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'611p','IVAN KORNIIENKO','PROGRAMMERS');
insert into groups values (2,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'621er','MORGAN FREEMAN','ECONOMISTS');
insert into groups values (3,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'632p','JOANNE ROWLING','PROGRAMMERS');
insert into groups values (4,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'511e','LEBRON JAMES','ECONOMISTS');
insert into groups values (5,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'411p','LEO MESSI','PROGRAMMERS');
insert into groups values (6,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'411e','IVAN KORNIIENKO','ECONOMISTS');
insert into groups values (7,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'611e','LEBRON JAMES','ECONOMISTS');
insert into groups values (8,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'622e','MORGAN FREEMAN','ECONOMISTS');
insert into groups values (9,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'621m','IVAN KORNIIENKO','MARKETERS');
insert into groups values (10,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'623p','JOANNE ROWLING','PROGRAMMERS');
insert into groups values (11,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'631p','IVAN KORNIIENKO','PROGRAMMERS');
insert into groups values (12,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'611m','MORGAN FREEMAN','MARKETERS');
insert into groups values (13,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'611m','LEBRON JAMES','MARKETERS');

insert into students values (1,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Aneta','Adaline','11');
insert into students values (2,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Assumpció','Grusha','22');
insert into students values (3,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Świętopełk','Zacharias','33');
insert into students values (4,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Nikoloz','Samuil','44');
insert into students values (5,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Melissza','Artemio','45');
insert into students values (6,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Kenya','Nuka','66');
insert into students values (7,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Candelario','Navin','23');
insert into students values (8,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Miroslava','Rada','47');
insert into students values (9,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Agata','Avdotya','41');
insert into students values (10,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Vasily','Anisim','14');
insert into students values (11,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Natalya','Markin','18');
insert into students values (12,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Natalya','Feofil','46');
insert into students values (13,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Lyudmila','Markin','23');
insert into students values (14,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Ivan','Dmitrii','19');
insert into students values (15,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Avdey','Markin','19');
insert into students values (16,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Lyudmila','Grusha','36');
insert into students values (17,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),'Avdey','Feofil','37');

insert into groups_students values (1,1,17);
insert into groups_students values (2,1,16);
insert into groups_students values (3,1,15);
insert into groups_students values (4,1,14);
insert into groups_students values (5,2,14);
insert into groups_students values (6,2,15);
insert into groups_students values (7,2,16);
insert into groups_students values (8,3,6);
insert into groups_students values (9,3,7);
insert into groups_students values (10,3,8);
insert into groups_students values (11,4,11);
insert into groups_students values (12,4,12);
insert into groups_students values (13,5,15);
insert into groups_students values (14,6,14);
insert into groups_students values (15,7,6);
insert into groups_students values (16,8,6);
insert into groups_students values (17,8,5);
insert into groups_students values (18,8,4);
insert into groups_students values (19,8,3);
insert into groups_students values (20,8,2);
insert into groups_students values (21,9,1);
insert into groups_students values (22,11,7);
insert into groups_students values (23,12,7);
insert into groups_students values (24,12,8);
insert into groups_students values (25,12,9);
insert into groups_students values (26,12,13);
insert into groups_students values (27,12,12);
insert into groups_students values (28,12,15);